# Generated by Django 5.0.1 on 2024-02-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('RD', 'Red'), ('WH', 'White')], default='RD', max_length=2)),
                ('region', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1, 'Year 16'), (2, 'Year 17'), (3, 'Year 18'), (4, 'Year 19'), (5, 'Year 20'), (6, 'Year 21'), (7, 'Year 22'), (8, 'Year 23'), (9, 'Year 24')], default=1)),
                ('alcohol_pct', models.DecimalField(decimal_places=1, max_digits=3)),
                ('preparation', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slogan', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
