# Generated by Django 5.0.1 on 2024-02-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_alter_wine_preparation_alter_wine_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
