# Generated by Django 5.0.1 on 2024-02-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_alter_wine_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='grape_variety',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
