# Generated by Django 5.0.1 on 2024-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_wine_grape_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='grape_variety',
            field=models.CharField(max_length=200),
        ),
    ]
