# Generated by Django 5.0.1 on 2024-02-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_alter_wine_grape_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.IntegerField(),
        ),
    ]
