# Generated by Django 5.0.1 on 2024-03-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0007_alter_wine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='cepage',
            field=models.CharField(default='default cepage', max_length=200),
            preserve_default=False,
        ),
    ]
